### ISSUE TITLE
Error while opening the add-on

### ISSUE THREAD

**Issue by MBozorgM** [chuanqixu/anki-quick-ai#6]
Error while opening the add-on

debug info:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\mbozorgmehr\AppData\Roaming\Anki2\addons21\547821970\controller.py", line 226, in run_add_on
    run_dialog = RunDialog(parent)
  File "C:\Users\mbozorgmehr\AppData\Roaming\Anki2\addons21\547821970\gui\run_dialog.py", line 21, in __init__
    self.initUI()
  File "C:\Users\mbozorgmehr\AppData\Roaming\Anki2\addons21\547821970\gui\run_dialog.py", line 32, in initUI
    self.provider_config = conf.get("ai_config." + provider_name)
TypeError: can only concatenate str (not "NoneType") to str

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Quick AI ['547821970', 2024-05-28T23:26, 'None', '']
Cross Profile Search and Import 20 ['1772763629', 2024-05-25T03:50, 'None', '']
Google Translate ['1536291224', 2024-05-08T17:46, 'None', mod]
HyperTTS - Add speech to your flashcards ['111623432', 2024-06-01T17:32, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T05:13, 'None', '']
Sentence adder for any language with batch add option ['1682655437', 2024-06-25T19:23, 'None', '']

===IDs of active AnkiWeb add-ons===
111623432 1536291224 1682655437 1771074083 1772763629 547821970

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by chuanqixu** [comment]
Thank you very much for posting this bug!

When first running the add-on, no provider name is stored in QSettings, which causes this issue.
